# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/harta55/Documents/Software/clion-2016.3.5/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/harta55/Documents/Software/clion-2016.3.5/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/harta55/ClionProjects/enTAP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/harta55/ClionProjects/enTAP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/harta55/Documents/Software/clion-2016.3.5/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/harta55/Documents/Software/clion-2016.3.5/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harta55/ClionProjects/enTAP/CMakeFiles /home/harta55/ClionProjects/enTAP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harta55/ClionProjects/enTAP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EnTAP

# Build rule for target.
EnTAP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EnTAP
.PHONY : EnTAP

# fast build rule for target.
EnTAP/fast:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/build
.PHONY : EnTAP/fast

src/DatabaseHelper.o: src/DatabaseHelper.cpp.o

.PHONY : src/DatabaseHelper.o

# target to build an object file
src/DatabaseHelper.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/DatabaseHelper.cpp.o
.PHONY : src/DatabaseHelper.cpp.o

src/DatabaseHelper.i: src/DatabaseHelper.cpp.i

.PHONY : src/DatabaseHelper.i

# target to preprocess a source file
src/DatabaseHelper.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/DatabaseHelper.cpp.i
.PHONY : src/DatabaseHelper.cpp.i

src/DatabaseHelper.s: src/DatabaseHelper.cpp.s

.PHONY : src/DatabaseHelper.s

# target to generate assembly for a file
src/DatabaseHelper.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/DatabaseHelper.cpp.s
.PHONY : src/DatabaseHelper.cpp.s

src/EntapConfig.o: src/EntapConfig.cpp.o

.PHONY : src/EntapConfig.o

# target to build an object file
src/EntapConfig.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapConfig.cpp.o
.PHONY : src/EntapConfig.cpp.o

src/EntapConfig.i: src/EntapConfig.cpp.i

.PHONY : src/EntapConfig.i

# target to preprocess a source file
src/EntapConfig.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapConfig.cpp.i
.PHONY : src/EntapConfig.cpp.i

src/EntapConfig.s: src/EntapConfig.cpp.s

.PHONY : src/EntapConfig.s

# target to generate assembly for a file
src/EntapConfig.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapConfig.cpp.s
.PHONY : src/EntapConfig.cpp.s

src/EntapExecute.o: src/EntapExecute.cpp.o

.PHONY : src/EntapExecute.o

# target to build an object file
src/EntapExecute.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapExecute.cpp.o
.PHONY : src/EntapExecute.cpp.o

src/EntapExecute.i: src/EntapExecute.cpp.i

.PHONY : src/EntapExecute.i

# target to preprocess a source file
src/EntapExecute.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapExecute.cpp.i
.PHONY : src/EntapExecute.cpp.i

src/EntapExecute.s: src/EntapExecute.cpp.s

.PHONY : src/EntapExecute.s

# target to generate assembly for a file
src/EntapExecute.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapExecute.cpp.s
.PHONY : src/EntapExecute.cpp.s

src/EntapGlobals.o: src/EntapGlobals.cpp.o

.PHONY : src/EntapGlobals.o

# target to build an object file
src/EntapGlobals.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapGlobals.cpp.o
.PHONY : src/EntapGlobals.cpp.o

src/EntapGlobals.i: src/EntapGlobals.cpp.i

.PHONY : src/EntapGlobals.i

# target to preprocess a source file
src/EntapGlobals.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapGlobals.cpp.i
.PHONY : src/EntapGlobals.cpp.i

src/EntapGlobals.s: src/EntapGlobals.cpp.s

.PHONY : src/EntapGlobals.s

# target to generate assembly for a file
src/EntapGlobals.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/EntapGlobals.cpp.s
.PHONY : src/EntapGlobals.cpp.s

src/ExceptionHandler.o: src/ExceptionHandler.cpp.o

.PHONY : src/ExceptionHandler.o

# target to build an object file
src/ExceptionHandler.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ExceptionHandler.cpp.o
.PHONY : src/ExceptionHandler.cpp.o

src/ExceptionHandler.i: src/ExceptionHandler.cpp.i

.PHONY : src/ExceptionHandler.i

# target to preprocess a source file
src/ExceptionHandler.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ExceptionHandler.cpp.i
.PHONY : src/ExceptionHandler.cpp.i

src/ExceptionHandler.s: src/ExceptionHandler.cpp.s

.PHONY : src/ExceptionHandler.s

# target to generate assembly for a file
src/ExceptionHandler.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ExceptionHandler.cpp.s
.PHONY : src/ExceptionHandler.cpp.s

src/ExpressionAnalysis.o: src/ExpressionAnalysis.cpp.o

.PHONY : src/ExpressionAnalysis.o

# target to build an object file
src/ExpressionAnalysis.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ExpressionAnalysis.cpp.o
.PHONY : src/ExpressionAnalysis.cpp.o

src/ExpressionAnalysis.i: src/ExpressionAnalysis.cpp.i

.PHONY : src/ExpressionAnalysis.i

# target to preprocess a source file
src/ExpressionAnalysis.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ExpressionAnalysis.cpp.i
.PHONY : src/ExpressionAnalysis.cpp.i

src/ExpressionAnalysis.s: src/ExpressionAnalysis.cpp.s

.PHONY : src/ExpressionAnalysis.s

# target to generate assembly for a file
src/ExpressionAnalysis.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ExpressionAnalysis.cpp.s
.PHONY : src/ExpressionAnalysis.cpp.s

src/FrameSelection.o: src/FrameSelection.cpp.o

.PHONY : src/FrameSelection.o

# target to build an object file
src/FrameSelection.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/FrameSelection.cpp.o
.PHONY : src/FrameSelection.cpp.o

src/FrameSelection.i: src/FrameSelection.cpp.i

.PHONY : src/FrameSelection.i

# target to preprocess a source file
src/FrameSelection.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/FrameSelection.cpp.i
.PHONY : src/FrameSelection.cpp.i

src/FrameSelection.s: src/FrameSelection.cpp.s

.PHONY : src/FrameSelection.s

# target to generate assembly for a file
src/FrameSelection.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/FrameSelection.cpp.s
.PHONY : src/FrameSelection.cpp.s

src/GraphingManager.o: src/GraphingManager.cpp.o

.PHONY : src/GraphingManager.o

# target to build an object file
src/GraphingManager.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/GraphingManager.cpp.o
.PHONY : src/GraphingManager.cpp.o

src/GraphingManager.i: src/GraphingManager.cpp.i

.PHONY : src/GraphingManager.i

# target to preprocess a source file
src/GraphingManager.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/GraphingManager.cpp.i
.PHONY : src/GraphingManager.cpp.i

src/GraphingManager.s: src/GraphingManager.cpp.s

.PHONY : src/GraphingManager.s

# target to generate assembly for a file
src/GraphingManager.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/GraphingManager.cpp.s
.PHONY : src/GraphingManager.cpp.s

src/Ontology.o: src/Ontology.cpp.o

.PHONY : src/Ontology.o

# target to build an object file
src/Ontology.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/Ontology.cpp.o
.PHONY : src/Ontology.cpp.o

src/Ontology.i: src/Ontology.cpp.i

.PHONY : src/Ontology.i

# target to preprocess a source file
src/Ontology.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/Ontology.cpp.i
.PHONY : src/Ontology.cpp.i

src/Ontology.s: src/Ontology.cpp.s

.PHONY : src/Ontology.s

# target to generate assembly for a file
src/Ontology.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/Ontology.cpp.s
.PHONY : src/Ontology.cpp.s

src/QueryData.o: src/QueryData.cpp.o

.PHONY : src/QueryData.o

# target to build an object file
src/QueryData.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/QueryData.cpp.o
.PHONY : src/QueryData.cpp.o

src/QueryData.i: src/QueryData.cpp.i

.PHONY : src/QueryData.i

# target to preprocess a source file
src/QueryData.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/QueryData.cpp.i
.PHONY : src/QueryData.cpp.i

src/QueryData.s: src/QueryData.cpp.s

.PHONY : src/QueryData.s

# target to generate assembly for a file
src/QueryData.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/QueryData.cpp.s
.PHONY : src/QueryData.cpp.s

src/QuerySequence.o: src/QuerySequence.cpp.o

.PHONY : src/QuerySequence.o

# target to build an object file
src/QuerySequence.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/QuerySequence.cpp.o
.PHONY : src/QuerySequence.cpp.o

src/QuerySequence.i: src/QuerySequence.cpp.i

.PHONY : src/QuerySequence.i

# target to preprocess a source file
src/QuerySequence.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/QuerySequence.cpp.i
.PHONY : src/QuerySequence.cpp.i

src/QuerySequence.s: src/QuerySequence.cpp.s

.PHONY : src/QuerySequence.s

# target to generate assembly for a file
src/QuerySequence.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/QuerySequence.cpp.s
.PHONY : src/QuerySequence.cpp.s

src/SimilaritySearch.o: src/SimilaritySearch.cpp.o

.PHONY : src/SimilaritySearch.o

# target to build an object file
src/SimilaritySearch.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/SimilaritySearch.cpp.o
.PHONY : src/SimilaritySearch.cpp.o

src/SimilaritySearch.i: src/SimilaritySearch.cpp.i

.PHONY : src/SimilaritySearch.i

# target to preprocess a source file
src/SimilaritySearch.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/SimilaritySearch.cpp.i
.PHONY : src/SimilaritySearch.cpp.i

src/SimilaritySearch.s: src/SimilaritySearch.cpp.s

.PHONY : src/SimilaritySearch.s

# target to generate assembly for a file
src/SimilaritySearch.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/SimilaritySearch.cpp.s
.PHONY : src/SimilaritySearch.cpp.s

src/UserInput.o: src/UserInput.cpp.o

.PHONY : src/UserInput.o

# target to build an object file
src/UserInput.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/UserInput.cpp.o
.PHONY : src/UserInput.cpp.o

src/UserInput.i: src/UserInput.cpp.i

.PHONY : src/UserInput.i

# target to preprocess a source file
src/UserInput.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/UserInput.cpp.i
.PHONY : src/UserInput.cpp.i

src/UserInput.s: src/UserInput.cpp.s

.PHONY : src/UserInput.s

# target to generate assembly for a file
src/UserInput.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/UserInput.cpp.s
.PHONY : src/UserInput.cpp.s

src/expression/ModRSEM.o: src/expression/ModRSEM.cpp.o

.PHONY : src/expression/ModRSEM.o

# target to build an object file
src/expression/ModRSEM.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/expression/ModRSEM.cpp.o
.PHONY : src/expression/ModRSEM.cpp.o

src/expression/ModRSEM.i: src/expression/ModRSEM.cpp.i

.PHONY : src/expression/ModRSEM.i

# target to preprocess a source file
src/expression/ModRSEM.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/expression/ModRSEM.cpp.i
.PHONY : src/expression/ModRSEM.cpp.i

src/expression/ModRSEM.s: src/expression/ModRSEM.cpp.s

.PHONY : src/expression/ModRSEM.s

# target to generate assembly for a file
src/expression/ModRSEM.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/expression/ModRSEM.cpp.s
.PHONY : src/expression/ModRSEM.cpp.s

src/frame_selection/ModGeneMarkST.o: src/frame_selection/ModGeneMarkST.cpp.o

.PHONY : src/frame_selection/ModGeneMarkST.o

# target to build an object file
src/frame_selection/ModGeneMarkST.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/frame_selection/ModGeneMarkST.cpp.o
.PHONY : src/frame_selection/ModGeneMarkST.cpp.o

src/frame_selection/ModGeneMarkST.i: src/frame_selection/ModGeneMarkST.cpp.i

.PHONY : src/frame_selection/ModGeneMarkST.i

# target to preprocess a source file
src/frame_selection/ModGeneMarkST.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/frame_selection/ModGeneMarkST.cpp.i
.PHONY : src/frame_selection/ModGeneMarkST.cpp.i

src/frame_selection/ModGeneMarkST.s: src/frame_selection/ModGeneMarkST.cpp.s

.PHONY : src/frame_selection/ModGeneMarkST.s

# target to generate assembly for a file
src/frame_selection/ModGeneMarkST.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/frame_selection/ModGeneMarkST.cpp.s
.PHONY : src/frame_selection/ModGeneMarkST.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ontology/AbstractOntology.o: src/ontology/AbstractOntology.cpp.o

.PHONY : src/ontology/AbstractOntology.o

# target to build an object file
src/ontology/AbstractOntology.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/AbstractOntology.cpp.o
.PHONY : src/ontology/AbstractOntology.cpp.o

src/ontology/AbstractOntology.i: src/ontology/AbstractOntology.cpp.i

.PHONY : src/ontology/AbstractOntology.i

# target to preprocess a source file
src/ontology/AbstractOntology.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/AbstractOntology.cpp.i
.PHONY : src/ontology/AbstractOntology.cpp.i

src/ontology/AbstractOntology.s: src/ontology/AbstractOntology.cpp.s

.PHONY : src/ontology/AbstractOntology.s

# target to generate assembly for a file
src/ontology/AbstractOntology.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/AbstractOntology.cpp.s
.PHONY : src/ontology/AbstractOntology.cpp.s

src/ontology/ModEggnog.o: src/ontology/ModEggnog.cpp.o

.PHONY : src/ontology/ModEggnog.o

# target to build an object file
src/ontology/ModEggnog.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/ModEggnog.cpp.o
.PHONY : src/ontology/ModEggnog.cpp.o

src/ontology/ModEggnog.i: src/ontology/ModEggnog.cpp.i

.PHONY : src/ontology/ModEggnog.i

# target to preprocess a source file
src/ontology/ModEggnog.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/ModEggnog.cpp.i
.PHONY : src/ontology/ModEggnog.cpp.i

src/ontology/ModEggnog.s: src/ontology/ModEggnog.cpp.s

.PHONY : src/ontology/ModEggnog.s

# target to generate assembly for a file
src/ontology/ModEggnog.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/ModEggnog.cpp.s
.PHONY : src/ontology/ModEggnog.cpp.s

src/ontology/ModInterpro.o: src/ontology/ModInterpro.cpp.o

.PHONY : src/ontology/ModInterpro.o

# target to build an object file
src/ontology/ModInterpro.cpp.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/ModInterpro.cpp.o
.PHONY : src/ontology/ModInterpro.cpp.o

src/ontology/ModInterpro.i: src/ontology/ModInterpro.cpp.i

.PHONY : src/ontology/ModInterpro.i

# target to preprocess a source file
src/ontology/ModInterpro.cpp.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/ModInterpro.cpp.i
.PHONY : src/ontology/ModInterpro.cpp.i

src/ontology/ModInterpro.s: src/ontology/ModInterpro.cpp.s

.PHONY : src/ontology/ModInterpro.s

# target to generate assembly for a file
src/ontology/ModInterpro.cpp.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/ontology/ModInterpro.cpp.s
.PHONY : src/ontology/ModInterpro.cpp.s

src/sqlite3.o: src/sqlite3.c.o

.PHONY : src/sqlite3.o

# target to build an object file
src/sqlite3.c.o:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/sqlite3.c.o
.PHONY : src/sqlite3.c.o

src/sqlite3.i: src/sqlite3.c.i

.PHONY : src/sqlite3.i

# target to preprocess a source file
src/sqlite3.c.i:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/sqlite3.c.i
.PHONY : src/sqlite3.c.i

src/sqlite3.s: src/sqlite3.c.s

.PHONY : src/sqlite3.s

# target to generate assembly for a file
src/sqlite3.c.s:
	$(MAKE) -f CMakeFiles/EnTAP.dir/build.make CMakeFiles/EnTAP.dir/src/sqlite3.c.s
.PHONY : src/sqlite3.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EnTAP"
	@echo "... src/DatabaseHelper.o"
	@echo "... src/DatabaseHelper.i"
	@echo "... src/DatabaseHelper.s"
	@echo "... src/EntapConfig.o"
	@echo "... src/EntapConfig.i"
	@echo "... src/EntapConfig.s"
	@echo "... src/EntapExecute.o"
	@echo "... src/EntapExecute.i"
	@echo "... src/EntapExecute.s"
	@echo "... src/EntapGlobals.o"
	@echo "... src/EntapGlobals.i"
	@echo "... src/EntapGlobals.s"
	@echo "... src/ExceptionHandler.o"
	@echo "... src/ExceptionHandler.i"
	@echo "... src/ExceptionHandler.s"
	@echo "... src/ExpressionAnalysis.o"
	@echo "... src/ExpressionAnalysis.i"
	@echo "... src/ExpressionAnalysis.s"
	@echo "... src/FrameSelection.o"
	@echo "... src/FrameSelection.i"
	@echo "... src/FrameSelection.s"
	@echo "... src/GraphingManager.o"
	@echo "... src/GraphingManager.i"
	@echo "... src/GraphingManager.s"
	@echo "... src/Ontology.o"
	@echo "... src/Ontology.i"
	@echo "... src/Ontology.s"
	@echo "... src/QueryData.o"
	@echo "... src/QueryData.i"
	@echo "... src/QueryData.s"
	@echo "... src/QuerySequence.o"
	@echo "... src/QuerySequence.i"
	@echo "... src/QuerySequence.s"
	@echo "... src/SimilaritySearch.o"
	@echo "... src/SimilaritySearch.i"
	@echo "... src/SimilaritySearch.s"
	@echo "... src/UserInput.o"
	@echo "... src/UserInput.i"
	@echo "... src/UserInput.s"
	@echo "... src/expression/ModRSEM.o"
	@echo "... src/expression/ModRSEM.i"
	@echo "... src/expression/ModRSEM.s"
	@echo "... src/frame_selection/ModGeneMarkST.o"
	@echo "... src/frame_selection/ModGeneMarkST.i"
	@echo "... src/frame_selection/ModGeneMarkST.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ontology/AbstractOntology.o"
	@echo "... src/ontology/AbstractOntology.i"
	@echo "... src/ontology/AbstractOntology.s"
	@echo "... src/ontology/ModEggnog.o"
	@echo "... src/ontology/ModEggnog.i"
	@echo "... src/ontology/ModEggnog.s"
	@echo "... src/ontology/ModInterpro.o"
	@echo "... src/ontology/ModInterpro.i"
	@echo "... src/ontology/ModInterpro.s"
	@echo "... src/sqlite3.o"
	@echo "... src/sqlite3.i"
	@echo "... src/sqlite3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

