# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/harta/Documents/clion-2016.3.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/harta/Documents/clion-2016.3.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/harta/CLionProjects/enTAP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/harta/CLionProjects/enTAP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/harta/Documents/clion-2016.3.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/harta/Documents/clion-2016.3.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harta/CLionProjects/enTAP/CMakeFiles /home/harta/CLionProjects/enTAP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/harta/CLionProjects/enTAP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named enTAP

# Build rule for target.
enTAP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enTAP
.PHONY : enTAP

# fast build rule for target.
enTAP/fast:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/build
.PHONY : enTAP/fast

EntapExecute.o: EntapExecute.cpp.o

.PHONY : EntapExecute.o

# target to build an object file
EntapExecute.cpp.o:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/EntapExecute.cpp.o
.PHONY : EntapExecute.cpp.o

EntapExecute.i: EntapExecute.cpp.i

.PHONY : EntapExecute.i

# target to preprocess a source file
EntapExecute.cpp.i:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/EntapExecute.cpp.i
.PHONY : EntapExecute.cpp.i

EntapExecute.s: EntapExecute.cpp.s

.PHONY : EntapExecute.s

# target to generate assembly for a file
EntapExecute.cpp.s:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/EntapExecute.cpp.s
.PHONY : EntapExecute.cpp.s

EntapInit.o: EntapInit.cpp.o

.PHONY : EntapInit.o

# target to build an object file
EntapInit.cpp.o:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/EntapInit.cpp.o
.PHONY : EntapInit.cpp.o

EntapInit.i: EntapInit.cpp.i

.PHONY : EntapInit.i

# target to preprocess a source file
EntapInit.cpp.i:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/EntapInit.cpp.i
.PHONY : EntapInit.cpp.i

EntapInit.s: EntapInit.cpp.s

.PHONY : EntapInit.s

# target to generate assembly for a file
EntapInit.cpp.s:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/EntapInit.cpp.s
.PHONY : EntapInit.cpp.s

ExceptionHandler.o: ExceptionHandler.cpp.o

.PHONY : ExceptionHandler.o

# target to build an object file
ExceptionHandler.cpp.o:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/ExceptionHandler.cpp.o
.PHONY : ExceptionHandler.cpp.o

ExceptionHandler.i: ExceptionHandler.cpp.i

.PHONY : ExceptionHandler.i

# target to preprocess a source file
ExceptionHandler.cpp.i:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/ExceptionHandler.cpp.i
.PHONY : ExceptionHandler.cpp.i

ExceptionHandler.s: ExceptionHandler.cpp.s

.PHONY : ExceptionHandler.s

# target to generate assembly for a file
ExceptionHandler.cpp.s:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/ExceptionHandler.cpp.s
.PHONY : ExceptionHandler.cpp.s

ExpressionAnalysis.o: ExpressionAnalysis.cpp.o

.PHONY : ExpressionAnalysis.o

# target to build an object file
ExpressionAnalysis.cpp.o:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/ExpressionAnalysis.cpp.o
.PHONY : ExpressionAnalysis.cpp.o

ExpressionAnalysis.i: ExpressionAnalysis.cpp.i

.PHONY : ExpressionAnalysis.i

# target to preprocess a source file
ExpressionAnalysis.cpp.i:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/ExpressionAnalysis.cpp.i
.PHONY : ExpressionAnalysis.cpp.i

ExpressionAnalysis.s: ExpressionAnalysis.cpp.s

.PHONY : ExpressionAnalysis.s

# target to generate assembly for a file
ExpressionAnalysis.cpp.s:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/ExpressionAnalysis.cpp.s
.PHONY : ExpressionAnalysis.cpp.s

FrameSelection.o: FrameSelection.cpp.o

.PHONY : FrameSelection.o

# target to build an object file
FrameSelection.cpp.o:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/FrameSelection.cpp.o
.PHONY : FrameSelection.cpp.o

FrameSelection.i: FrameSelection.cpp.i

.PHONY : FrameSelection.i

# target to preprocess a source file
FrameSelection.cpp.i:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/FrameSelection.cpp.i
.PHONY : FrameSelection.cpp.i

FrameSelection.s: FrameSelection.cpp.s

.PHONY : FrameSelection.s

# target to generate assembly for a file
FrameSelection.cpp.s:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/FrameSelection.cpp.s
.PHONY : FrameSelection.cpp.s

QuerySequence.o: QuerySequence.cpp.o

.PHONY : QuerySequence.o

# target to build an object file
QuerySequence.cpp.o:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/QuerySequence.cpp.o
.PHONY : QuerySequence.cpp.o

QuerySequence.i: QuerySequence.cpp.i

.PHONY : QuerySequence.i

# target to preprocess a source file
QuerySequence.cpp.i:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/QuerySequence.cpp.i
.PHONY : QuerySequence.cpp.i

QuerySequence.s: QuerySequence.cpp.s

.PHONY : QuerySequence.s

# target to generate assembly for a file
QuerySequence.cpp.s:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/QuerySequence.cpp.s
.PHONY : QuerySequence.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/enTAP.dir/build.make CMakeFiles/enTAP.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... enTAP"
	@echo "... EntapExecute.o"
	@echo "... EntapExecute.i"
	@echo "... EntapExecute.s"
	@echo "... EntapInit.o"
	@echo "... EntapInit.i"
	@echo "... EntapInit.s"
	@echo "... ExceptionHandler.o"
	@echo "... ExceptionHandler.i"
	@echo "... ExceptionHandler.s"
	@echo "... ExpressionAnalysis.o"
	@echo "... ExpressionAnalysis.i"
	@echo "... ExpressionAnalysis.s"
	@echo "... FrameSelection.o"
	@echo "... FrameSelection.i"
	@echo "... FrameSelection.s"
	@echo "... QuerySequence.o"
	@echo "... QuerySequence.i"
	@echo "... QuerySequence.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system


